export const CHANGE_INPUT = 'change_input'
export const ADD_LIST = 'add_list'
export const DELETE_ITEM = 'delete_item' 
export const INIT_LIST = 'init_list'
export const GET_INIT_LIST = 'get_init_list'